version: '3.7'

services:
  db:
    image: postgres
    deploy:
      resources:
        limits:
          cpus: '0.75'
          memory: '1.5GB'
    environment:
      POSTGRES_USER: "quarkus"
      POSTGRES_PASSWORD: "quarkus"
      POSTGRES_DB: "rinha-dev"
    ports:
      - "5432:5432"
    healthcheck:
      test: pg_isready -U postgres
   # command: dockerize -wait tcp://db:5432 -timeout 60s
  api1: &app # API - Instância 01
    image: jslima/rinha-dev-java:latest
    hostname: api1
    depends_on:
      db:
        condition: service_healthy
    expose:
      - "8080"
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '0.5GB'
    environment:
      URL_DATABASE: "postgresql://db:5432/rinha-dev"
      DATABASE_USERNAME: "quarkus"
      DATABASE_PASSWORD: "quarkus"
      LOG_LEVEL: "DEBUG"
      LOG_SQL: "false"
  #  command: dockerize -wait tcp://db:5432 -timeout 60s
  api2: # API - Instância 01
    <<: *app
    hostname: api2
  nginx: # Load Balancer
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '0.5GB'