version: '3.7'

services:
  db:
    image: postgres
    deploy:
      resources:
        limits:
          cpus: '0.75'
          memory: '1.5GB'
    environment:
      POSTGRES_USER: "quarkus"
      POSTGRES_PASSWORD: "quarkus"
      POSTGRES_DB: "rinha-dev"
    ports:
      - "5432:5432"
#  api1: # API - Instância 01
#    image: quarkus/rinha-dev-java
#    hostname: api1
#    depends_on:
#      - db
#    expose:
#      - "8080"
#    deploy:
#      resources:
#        limits:
#          cpus: '0.25'
#          memory: '0.5GB'
#  api2: # API - Instância 01
#    image: quarkus/rinha-dev-java
#    hostname: api2
#    depends_on:
#      - db
#    expose:
#      - "8080"
#    deploy:
#      resources:
#        limits:
#          cpus: '0.25'
#          memory: '0.5GB'
#  nginx: # Load Balancer
#    image: nginx:latest
#    volumes:
#      - ./nginx.conf:/etc/nginx/nginx.conf:ro
#    depends_on:
#      - api1
#      - api2
#    ports:
#      - "9999:9999"
#    deploy:
#      resources:
#        limits:
#          cpus: '0.25'
#          memory: '0.5GB'